### DISCUSSION TITLE
RFC: Theme support for HydePHP Markdown Pages?

### DISCUSSION THREAD

**Discussion by emmadesilva** [hydephp/develop#1383] [Internals]
**This proposal is formatted using the proposed new Markdown spec, in the same way a Themed Markdown page would be.**
````markdown
---
title: "Presenting the Hyde SmartTheme Experiment"
theme: demo // Sets the page theme
---

The Hyde SmartTheme Experiment explores the idea of a superset of Markdown
that allows for rich and dynamic control over component-based templates
through code blocks embedded in the Markdown.

By using Yaml code blocks, we can specify the component name and any data
provided to it. This will provide a way to rapidly construct simple pages,
right alongside your Markdown. Since we are exploiting Markdown code
blocks, we even get IDE support and syntax highlighting!

```yaml header
title: "My Header Title"
lead: "Example lead text"
description: "This will render the 'header' component with this Yaml data passed to the view"
```

This would provide a bunch of new interesting opportunities.

Pros:
- Novel approach to Markdown-based pages
- Rapid construction of pages

Cons:
- Dependent on third party themes which may have varying quality
- When initially developing HydePHP, I (the author) intentionally
  made the decision to not support themes due to the complexity,
  bloat, and the risk of overwhelming the user with options.
  For this reason, I chose to instead focus on including
  a versatile and high quality starter template.
  This also distinguishes us from Jekyll.

With these considerations in mind, and any that users are encouraged to submit,
what does the community think about this proposal? Is this something you'd
be interested in seeing? What are your thoughts on the spec?

Please let me know!
````

**Comment by emmadesilva** [comment]
**Alternative syntaxes**

````markdown
# UI Components using Markdown Code Blocks

```hyde-component welcome
yaml: data
pros: shorter syntax, unique, has no conflicts
cons: verbose, requires an IDE plugin
```

```component welcome
yaml: data
pros: unique, has no conflicts
cons: verbose, requires an IDE plugin
```

```yaml hyde-component welcome
yaml: data
pros: has built in IDE support, reduces conflicts, and makes it clearer it's a Hyde component
cons: verbose, the usage of `yaml` as the initial key may be confusing, may have conflicts
```

```yaml welcome
yaml: data
pros: short syntax, has built in IDE support,
cons: the usage of `yaml` as the initial key may be confusing, lack of component keyword may also be confusing. highest risk of conflicts
```
````

At some point though, this almost becomes a new language and it would lose out on the intended user friendliness. A big bonus with the Yaml syntax compared to a Blade component library however is that this can be managed using a visual frontend, as the Yaml data is fully machine readable/writable.
