### ISSUE TITLE
Some way to edit documentation page configuration within the `hyde.yml` file

### ISSUE THREAD

**Issue by caendesilva** [hydephp/develop#1341]
Something I realize now that we're missing is a way to edit documentation settings from the Yaml configuration file. Not sure what the best way to do this is though.

**Comment by caendesilva** [comment]
### Asking ChatGPT:

#### GPT Prompt

```
I have a framework which provides a set of config files as follows:
config/hyde.php
config/docs.php
config/markdown.php

I also have a feature which allows the user to define the settings in config/hyde.php in a Yaml file stored as hyde.yml. I am now looking to allow the settings in the config/docs.php file in the hyde.yml file. What would be the most elegant way to incorporate this?
```

#### Response

One possible solution is to use a nested structure in the Yaml file, where each config file is represented by a key and its settings are represented by nested keys. For example:

```yaml
hyde:
  setting1: value1
  setting2: value2
docs:
  setting3: value3
  setting4: value4
markdown:
  setting5: value5
```

#### Follow up prompt:

```
I thought of that too, but the addition must be fully backwards compatible.
```

In that case, you could provide a default value for the docs key in the hyde.yml file, which will only be used if the user explicitly defines it. For example:


```yaml
hyde:
  setting1: value1
  setting2: value2
  docs:
    setting3: value3
    setting4: value4
markdown:
  setting5: value5
```

> Note: It doesn't seem like it understood my request.

**Comment by caendesilva** [comment]
Another alternative is to have a docs.yml file but at that point we lose the whole point with having a single easily modifiable file. So I think a top-level `docs` entry would be best. Or possible, a special prefix to distinguish it. Sadly, I closed GPT and the history feature is broken. But I'll start hacking on this, the prefix is easy to change later.

**Comment by caendesilva** [comment]
> Another alternative is to have a docs.yml file but at that point we lose the whole point with having a single easily modifiable file. So I think a top-level `docs` entry would be best. Or possible, a special prefix to distinguish it. Sadly, I closed GPT and the history feature is broken. But I'll start hacking on this, the prefix is easy to change later.


I feel like it's a bit "hacky" to add an extra key, which is not mapped to one in the `hyde.php` config file. An alternative that would be compatible, is to support all configuration options by checking if the entire file is indented.

So a file like this:
```yml
setting1: value1
setting2: value2
```
Would have the current behaviour

But a file like this:
```yaml
hyde:
  setting1: value1
  setting2: value2
```
would allow for more options. For example

```yaml
hyde:
  setting1: value1
  setting2: value2
docs:
  setting3: value3
  setting4: value4
markdown:
  setting5: value5
```

Depending on the underlying implementation this could be automatically enabled for any arbitrary config file, even allowing vendor configs to be used. Maybe by checking the top-level key with the global root config keys.
