### ISSUE TITLE
Simplified featured image schema for blog posts

### ISSUE THREAD

**Issue by caendesilva** [hydephp/develop#1718]
Okay, I'm gonna be honest here. I _in theory_ love that HydePHP can assemble dynamic featured image captions. But in practise, it doesn't work. I wrote the code and designed the schema, and I still can never remember what the accepted properties are. I think for v2, it's worth the BC break to simplify these. Stuff like `altText` and `licenseUrl` is just too hard to remember.

Instead, this would be much better, to have a literal caption field instead of dynamic data items:

```yaml
image:
    source: how-to-turn-your-github-readme-into-a-static-website-cropped.png
    alt: Example of a static website created from a GitHub Readme
    caption: Static website from GitHub Readme
```

If alt text is not set, but caption is, then we can use the caption as the alt.

If we wanted to have fun, we can have a migration script that converts the old files into the new format by assembling the fields according to the v1 rules.
