### ISSUE TITLE
Improve the author feature to allow more schema fields

### ISSUE THREAD

**Issue by caendesilva** [hydephp/develop#1778]
We should include a field for the author's biography. We may also want to support more socials.

We may also want to consider keying the array, to make the username relationship more explicit. This means we would do this for v2.

A good idea could be to utalize the formats and conventions from Jekyll https://github.com/gouravkhunger/jekyll-auto-authors

```yaml
username1:
  name: 'User 1'
  bio: 'Bio of user 1'
  website: 'http://user1.com'
  socials:
    twitter: '@user1'
    github: 'user1'

username2:
  name: 'User 2'
  bio: 'Bio of user 2'
  website: 'http://user2.com'
  socials:
    twitter: '@user2'
    github: 'user2'

test:
  exclude: true # Skips author from autopage generation only if they have no post assigned.
  name: 'Test user'
  bio: 'Bio of test user'
  website: 'http://test.com'
  socials:
    twitter: '@test'
    github: 'test'
```
