### ISSUE TITLE
Add easy to use post-build hooks

### ISSUE THREAD

**Issue by caendesilva** [hydephp/develop#79]
For example, in the HydePHP.com CI we create a few files in the GitHub workflow. These could just as easily be made in a post build hook.

```yaml

    - name: Create .nojekyll
      run: touch _site/.nojekyll
      
    - name: Create CNAME
      run: echo "hydephp.com" > _site/CNAME

```
